#!/bin/bash
shells=/home/suguannan/MyShells
PATH=$PATH:$shells
shCmd=`which sh`
$shCmd $shells/memory &
$shCmd $shells/load_avg &
$shCmd $shells/disk &
$shCmd $shells/cpu_time &
$shCmd $shells/traffic &
exit 0
