#!/bin/bash

# source cfg file
. /usr/local/IPTVAgent/cfg/iptvagent.cfg

for file in `ls $tmpPath`
    do
        if [ $file != 'realtime.tmp' ]; then
            rm $tmpPath/$file
        fi
    done

recordTime=`date -d today +"%Y-%m-%d %H:%M:%S"`
echo "[$recordTime] [INFO] Start a new round of collecting">> $logPath/iptvagent.log

# collect information
$modulePath/memory & 
$modulePath/load_avg &
$modulePath/disk &
$modulePath/cpu &
$modulePath/traffic &
$modulePath/mysql &
$modulePath/nginx &
$modulePath/streams &
$modulePath/io &
exit 0
