#!/bin/bash
result=$(/bin/df -Ph | awk 'NR>1 { if($1~/\/dev/){
{print "{\"file_system\": \"" $1 "\", \"size\": \"" $2 "\", \"used\": \"" $3 "\", \"avail\": \"" $4 "\", \"used%\":"} 
{printf("\"%.2f",$5)}{print"%\",\"avail%\":"}
{printf("\"%.2f",$4/$2*100)}{print "%\"}"} }
}')

echo [ ${result%?} ]
