#! /bin/bash
#get the real path of parent folder
SOURCE="$0"
while [ -h "$SOURCE"  ]; do # resolve $SOURCE until the file is no longer a symlink
    DIR="$( cd -P "$( dirname "$SOURCE"  )" && pwd  )"
    SOURCE="$(readlink "$SOURCE")"
    [[ $SOURCE != /*  ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE"  )" && pwd  )"
#execute shellscripts
shells=${DIR}
. $shells/getProcessInfo
#initialize parameters to login mysql
hostnameCmd=`which hostname`
server=`$hostnameCmd`
Host=localhost
User=root
Password=111111
sql="select processName from iptvm.process where server ='$server';"
mysql=`which mysql`
MYSQL="$mysql -h$Host -u$User -p$Password --default-character-set=utf8 -A -N"
names=("$($MYSQL -e "$sql")")    
for name in ${names[*]}
   do
      echo $name
      getProcessInfo $name
   done
