#!/bin/bash
function insert()
 { 
insert=`echo $@`
Host=localhost
User=root
Password=123
MYSQL=`which mysql`
MSG=`$MYSQL -h$Host -u$User -p$Password<< EOF
        use iptvm;
        $insert
        exit
        EOF`    
echo $MSG
echo "finished"
}

