#!/bin/bash
echoCmd=`which echo`
function insert()
 { 
insert=`$echoCmd $@`
Host=localhost
User=root
Password=111111
MYSQL=`which mysql`
MSG=`$MYSQL -h$Host -u$User -p$Password<< EOF
        use iptvm;
        $insert
        exit
        EOF`    
$echoCmd $MSG
$echoCmd "finished"
}

