#!/bin/bash
shells=/home/suguannan/MyShells
PATH=$PATH:$shells
. $shells/insert
grepCmd=`which grep`
awkCmd=`which awk`
catCmd=`which cat`
numberOfCores=$($grepCmd -c 'processor' /proc/cpuinfo)
if [ $numberOfCores -eq 0 ]; then
	numberOfCores=1
fi
recordTime=`date -d today +"%Y-%m-%d %H:%M:%S"`
rst=$($catCmd /proc/loadavg | $awkCmd '{print ($1*100)/'$numberOfCores'"," ($2*100)/'$numberOfCores' "," ($3*100)/'$numberOfCores'"," $4 }')
load1=$(echo $rst|$awkCmd -F"," '{print $1}')
load5=$(echo $rst|$awkCmd -F"," '{print $2}')
load15=$(echo $rst|$awkCmd -F"," '{print $3}')
processRun=$(echo $rst|$awkCmd -F"," '{print $4}'|$awkCmd -F"/" '{print $1}')
processTotal=$(echo $rst|$awkCmd -F"," '{print $4}'|$awkCmd -F"/" '{print $2}')
SQLINSERT="insert into loads(load1,load5,load15,processRun,processTotal,recordTime,server) values($load1,$load5,$load15,$processRun,$processTotal,\"$recordTime\",\"localcent\");"
echo $SQLINSERT
insert $SQLINSERT

