#!/bin/bash

# source functions
. /usr/local/IPTVAgent/lib/functions

server=`hostname`
numberOfCores=$(grep -c 'processor' /proc/cpuinfo)

if [ $numberOfCores -eq 0 ]; then
	numberOfCores=1
fi
#recordTime=`date -d today +"%Y-%m-%d %H:%M:%S"`
recordTime=`date +"%s"`
rst=$(cat /proc/loadavg | awk '{print ($1*100)/'$numberOfCores'"," ($2*100)/'$numberOfCores' "," ($3*100)/'$numberOfCores'"," $4 }')
load1=$(echo $rst|awk -F"," '{print $1}')
load5=$(echo $rst|awk -F"," '{print $2}')
load15=$(echo $rst|awk -F"," '{print $3}')
processRun=$(echo $rst|awk -F"," '{print $4}'|awk -F"/" '{print $1}')
processTotal=$(echo $rst|awk -F"," '{print $4}'|awk -F"/" '{print $2}')

SQLINSERT="insert into loads(load1,load5,load15,processRun,processTotal,recordTime,server) values($load1,$load5,$load15,$processRun,$processTotal,\"$recordTime\",\"$server\");"

echo $SQLINSERT
insert $SQLINSERT

