#!/bin/bash

# source functions
. /usr/local/IPTVAgent/lib/functions

server=`hostname`
recordTime=`date -d today +"%Y-%m-%d %H:%M:%S"`

result=$(cat /proc/meminfo \
        | sed 's/':'/''/' \
	    | awk -F' '   \
        '{if($1=="MemTotal"||$1=="MemFree"||$1=="Buffers"||$1=="Cached"||$1=="Active"||$1=="MemAvailable") print "\""$1"\":\""$2"\","}' \
	    | sed 'N;$s/,\n/\n/;P;D' \
        )

space=' '
left_brace='{'
right_brace='}'
quote='\"'
colon=':'

temp_str=$(echo $result  \
        | sed "s/$space$left_brace$right_brace//g"  \
        | sed "s/$quote//g"  \
        | awk -F','   \
        '{for(iCnt=1;iCnt<=NF;iCnt++) print ""$iCnt""}'  \
        )
total=$(echo $temp_str | awk  -F' '   \
        '{for(iCnt=1;iCnt<=NF;iCnt++){if($iCnt~/^MemTotal/) print ""$iCnt""}}' \
        | awk -F':'   \
        '{print ""$2""}'  \
        )
free=$(echo $temp_str | awk  -F' '   \
        '{for(iCnt=1;iCnt<=NF;iCnt++){if($iCnt~/^MemFree/) print ""$iCnt""}}' \
        | awk -F':'   \
        '{print ""$2""}'  \
        )
buffer=$(echo $temp_str | awk  -F' '   \
        '{for(iCnt=1;iCnt<=NF;iCnt++){if($iCnt~/^Buffers/) print ""$iCnt""}}' \
        | awk -F':'   \
        '{print ""$2""}'  \
        )
cache=$(echo $temp_str | awk  -F' '   \
        '{for(iCnt=1;iCnt<=NF;iCnt++){if($iCnt~/^Cache/) print ""$iCnt""}}' \
        | awk -F':'   \
        '{print ""$2""}'  \
        )
used=`echo "scale=0; ($total-$free-$buffer-$cache)"|bc| awk '{printf "%.0f", $0}'`
utilize=`echo "scale=4; ($total-$free-$buffer-$cache)/$total*100"|bc|awk '{printf "%.2f", $0}'`

SQLINSERT="insert into memory(free,used,buffer,cache,total,utilize,recordTime,server) values($free,$used,$buffer,$cache,$total,$utilize,\"$recordTime\",\"$server\");"

echo $SQLINSERT
insert $SQLINSERT
