#!/bin/bash
shells=/home/suguannan/MyShells
PATH=$PATH:$shells
. $shells/insert
recordTime=`date -d today +"%Y-%m-%d %H:%M:%S"`
result=$(/bin/cat /proc/meminfo \
        | /bin/sed 's/':'/''/' \
	| /usr/bin/awk -F' '   \
       '{if($1=="MemTotal"||$1=="MemFree"||$1=="Buffers"||$1=="Cached"||$1=="Active"||$1=="MemAvailable") print "\""$1"\":\""$2"\","}' \
	| /bin/sed 'N;$s/,\n/\n/;P;D' \
        )
space=' '
left_brace='{'
right_brace='}'
quote='\"'
colon=':'
temp_str=$(/bin/echo $result  \
        | /bin/sed "s/$space$left_brace$right_brace//g"  \
        | /bin/sed "s/$quote//g"  \
        | /usr/bin/awk -F','   \
         '{for(iCnt=1;iCnt<=NF;iCnt++) print ""$iCnt""}'  \
         )
total=$(/bin/echo $temp_str | /usr/bin/awk  -F' '   \
         '{for(iCnt=1;iCnt<=NF;iCnt++){if($iCnt~/^MemTotal/) print ""$iCnt""}}' \
        | /usr/bin/awk -F':'   \
         '{print ""$2""}'  \
         )
free=$(/bin/echo $temp_str | /usr/bin/awk  -F' '   \
         '{for(iCnt=1;iCnt<=NF;iCnt++){if($iCnt~/^MemFree/) print ""$iCnt""}}' \
        | /usr/bin/awk -F':'   \
         '{print ""$2""}'  \
         )
buffer=$(/bin/echo $temp_str | /usr/bin/awk  -F' '   \
         '{for(iCnt=1;iCnt<=NF;iCnt++){if($iCnt~/^Buffers/) print ""$iCnt""}}' \
        | /usr/bin/awk -F':'   \
         '{print ""$2""}'  \
         )
cache=$(/bin/echo $temp_str | /usr/bin/awk  -F' '   \
         '{for(iCnt=1;iCnt<=NF;iCnt++){if($iCnt~/^Cache/) print ""$iCnt""}}' \
        | /usr/bin/awk -F':'   \
         '{print ""$2""}'  \
         )
used=`echo "scale=0; ($total-$free-$buffer-$cache)"|bc| awk '{printf "%.0f", $0}'`
utilize=`echo "scale=4; ($total-$free-$buffer-$cache)/$total*100"|bc|awk '{printf "%.2f", $0}'`
SQLINSERT="insert into memory(free,used,buffer,cache,total,utilize,recordTime,server) values($free,$used,$buffer,$cache,$total,$utilize,\"$recordTime\",\"localcent\");"
echo $SQLINSERT
insert $SQLINSERT
