#! /bin/bash
echoCmd=`which echo`
sleepCmd=`which sleep`
awkCmd=`which awk`
dateCmd=`which date`
testCmd=`which test`
Host=localhost
User=root
MYSQL=`which mysql`
hostnameCmd=`which hostname`
server=`$hostnameCmd`
#get the real path of parent folder
SOURCE="$0"
while [ -h "$SOURCE"  ]; do # resolve $SOURCE until the file is no longer a symlink
    DIR="$( cd -P "$( dirname "$SOURCE"  )" && pwd  )"
    SOURCE="$(readlink "$SOURCE")"
    [[ $SOURCE != /*  ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE"  )" && pwd  )"
shells=${DIR}
. $shells/insert
#Bytes_received,Bytes_sent,Com_commit,Com_rollback,Questions,Threads_connected,Threads_running
select="show global status where \`variable_name\` = 'Threads_connected' or \`variable_name\` = 'Threads_running' or \`variable_name\` = 'Questions' or \`variable_name\` = 'Com_commit' or \`variable_name\` = 'Com_rollback' or \`variable_name\` = 'Bytes_received' or \`variable_name\` = 'Bytes_sent';"
#get mysql info for the first time
resultPrev="$(${MYSQL} -h${Host} -u${User} -N -e "$select")"
#sleep for a second 
$sleepCmd 1s
#get mysql info for the second time
recordTime=`$dateCmd -d today +"%Y-%m-%d %H:%M:%S"`
result="$(${MYSQL} -h${Host} -u${User} -N -e "$select")"
if (`$testCmd -n "$resultPrev"`&&`$testCmd -n "$result"`);then
#if results not null, process the results acquired
bytesReceivedPrev=$($echoCmd $resultPrev | $awkCmd '{print $2}')
bytesReceived=$($echoCmd $result | $awkCmd '{print $2}')
bytesSentPrev=$($echoCmd $resultPrev | $awkCmd '{print $4}')
bytesSent=$($echoCmd $result | $awkCmd '{print $4}')
com_commitPrev=$($echoCmd $resultPrev | $awkCmd '{print $6}')
com_commit=$($echoCmd $result | $awkCmd '{print $6}')
com_rollbackPrev=$($echoCmd $resultPrev | $awkCmd '{print $8}')
com_rollback=$($echoCmd $result | $awkCmd '{print $8}')
questionsPrev=$($echoCmd $resultPrev | $awkCmd '{print $10}')
questions=$($echoCmd $result | $awkCmd '{print $10}')
let "receiveTraffic=$bytesReceived-$bytesReceivedPrev"
let "sendTraffic=$bytesSent-$bytesSentPrev"
let "qps=$questions-$questionsPrev"
let "tps=($com_commit+$com_rollback)-($com_commitPrev+$com_rollbackPrev)"
totalConnections=$($echoCmd $result | $awkCmd '{print $12}')
activeConnections=$($echoCmd $result | $awkCmd '{print $14}') 
SQLINSERT="insert into mysql_info(status,totalConnections,activeConnections,qps,tps,receiveTraffic,sendTraffic,recordTime,server) values(1,$totalConnections,$activeConnections,$qps,$tps,$receiveTraffic,$sendTraffic,\"$recordTime\",\"$server\");"
else 
SQLINSERT="insert into mysql_info(status,totalConnections,activeConnections,qps,tps,receiveTraffic,sendTraffic,recordTime,server) values(0,0,0,0,0,0,0,\"$recordTime\",\"$server\");"
fi
$echoCmd $SQLINSERT
insert $SQLINSERT



