#! /bin/bash
curlCmd=`which curl`
echoCmd=`which echo`
awkCmd=`which awk`
hostnameCmd=`which hostname`
testCmd=`which test`
dateCmd=`which date`
exec 2>/dev/null
#get the real path of parent folder
SOURCE="$0"
while [ -h "$SOURCE"  ]; do # resolve $SOURCE until the file is no longer a symlink
    DIR="$( cd -P "$( dirname "$SOURCE"  )" && pwd  )"
    SOURCE="$(readlink "$SOURCE")"
    [[ $SOURCE != /*  ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE"  )" && pwd  )"
shells=${DIR}
. $shells/insert
server=`$hostnameCmd`
#get nginx status
recordTime=`$dateCmd -d today +"%Y-%m-%d %H:%M:%S"`
result=$($echoCmd `$curlCmd http://127.0.0.1/nginx_status`)
if(`$testCmd -n "$result"`); then
accept=$($echoCmd $result|$awkCmd 'NR=4{print $8}')
handle=$($echoCmd $result|$awkCmd 'NR=4{print $9}')
active=$($echoCmd $result|$awkCmd 'NR=4{print $3}')
request=$($echoCmd $result|$awkCmd 'NR=4{print $10}')
readRequest=$($echoCmd $result|$awkCmd 'NR=4{print $12}')
writeRequest=$($echoCmd $result|$awkCmd 'NR=4{print $14}')
wait=$($echoCmd $result|$awkCmd 'NR=4{print $16}')
qps=0
responseTime=0
SQLINSERT="insert into nginx(accept,handle,request,active,readRequest,writeRequest,wait,readByte,writeByte,wait,qps,responseTime,recordTime,server) values($accept,$handle,$request,$active,$readRequest,$writeRequest,$wait,-1,-1,\"$recordTime\",\"$server\");"
fi
echo $SQLINSERT
