#! /bin/bash

# source functions
. /usr/local/IPTVAgent/lib/functions

server=`hostname`

##get cpu statistics for the first time
prevCPU=(`sed -n 's/^cpu\s//p' /proc/stat`)
prevTOTAL=0
for VALUE in "${prevCPU[@]}"; 
  do
    let "prevTOTAL=$prevTOTAL+$VALUE"
  done
prevIdleTime=${prevCPU[3]}
prevWait=${prevCPU[4]}
prevSteal=${prevCPU[7]}

##sleep for a while
sleep 1

##get cpu statistics for the second time
CPU=(`sed -n 's/^cpu\s//p' /proc/stat`)
TOTAL=0
for VALUE in "${CPU[@]}"; 
  do
    let "TOTAL=$TOTAL+$VALUE"
  done
idleTime=${CPU[3]}
wait=${CPU[4]}
steal=${CPU[7]}

##get 1min average load
numberOfCores=$(grep -c 'processor' /proc/cpuinfo)
if [ $numberOfCores -eq 0 ]; then
	numberOfCores=1
fi
load1=$(cat /proc/loadavg | awk '{print ($1*100)/'$numberOfCores' }')

##get memory statistics and calculate memory util rate
result=$(cat /proc/meminfo \
        | sed 's/':'/''/' \
    	| awk -F' '   \
        '{if($1=="MemTotal"||$1=="MemFree"||$1=="Buffers"||$1=="Cached"||$1=="Active"||$1=="MemAvailable") print "\""$1"\":\""$2"\","}' \
	    | sed 'N;$s/,\n/\n/;P;D' \
        )
space=' '
left_brace='{'
right_brace='}'
quote='\"'
colon=':'
temp_str=$(echo $result  \
        | sed "s/$space$left_brace$right_brace//g"  \
        | sed "s/$quote//g"  \
        | awk -F','   \
         '{for(iCnt=1;iCnt<=NF;iCnt++) print ""$iCnt""}'  \
         )
total=$(echo $temp_str | awk  -F' '   \
        '{for(iCnt=1;iCnt<=NF;iCnt++){if($iCnt~/^MemTotal/) print ""$iCnt""}}' \
        | awk -F':'   \
        '{print ""$2""}'  \
        )
free=$(echo $temp_str | awk  -F' '   \
        '{for(iCnt=1;iCnt<=NF;iCnt++){if($iCnt~/^MemFree/) print ""$iCnt""}}' \
        | awk -F':'   \
        '{print ""$2""}'  \
        )
buffer=$(echo $temp_str | awk  -F' '   \
        '{for(iCnt=1;iCnt<=NF;iCnt++){if($iCnt~/^Buffers/) print ""$iCnt""}}' \
        | awk -F':'   \
        '{print ""$2""}'  \
        )
cache=$(echo $temp_str | awk  -F' '   \
        '{for(iCnt=1;iCnt<=NF;iCnt++){if($iCnt~/^Cache/) print ""$iCnt""}}' \
        | awk -F':'   \
        '{print ""$2""}'  \
        )
memoryUtilize=`echo "scale=4; ($total-$free-$buffer-$cache)/$total*100"|bc|awk '{printf "%.2f", $0}'`

##get disk statistics and calculate disk util rate
rst=$(df -k | awk 'NR>1{a+=$4;b+=$3;c+=$2}END{print a","b","c}')
used=$(echo $rst | awk -F ',' '{print $2}')
used=`echo "scale=2;$used/1024/1024"|bc| awk '{printf "%.2f", $0}'`
total=$(echo $rst | awk -F ',' '{print $3}')
total=`echo "scale=2;$total/1024/1024"|bc| awk '{printf "%.2f", $0}'`
diskUtilize=`echo "scale=4;$used/$total*100"|bc| awk '{printf "%.2f", $0}'`

##calculate the cpu util rate
let "diffTOTAL=$TOTAL-$prevTOTAL"
let "diffIdleTime=$idleTime-$prevIdleTime"
let "diffWait=$wait-$prevWait"
let "diffSteal=$steal-$prevSteal"
cpuUtilize=`echo "scale=4;(1-$diffIdleTime/$diffTOTAL-$diffWait/$diffTOTAL-$diffSteal/$diffTOTAL)*100"|bc| awk '{printf "%.2f", $0}'`
SQLINSERT="insert into realtime(cpuUtilize,memoryUtilize,diskUtilize,load1,server) values($cpuUtilize,$memoryUtilize,$diskUtilize,$load1,\"$server\")ON DUPLICATE KEY update cpuUtilize=$cpuUtilize,memoryUtilize=$memoryUtilize,diskUtilize=$diskUtilize,load1=$load1;"
#echo $SQLINSERT
insert $SQLINSERT
