#! /bin/bash
#get the real path of parent folder
 SOURCE="$0"
 while [ -h "$SOURCE"  ]; do # resolve $SOURCE until the file is no longer a symlink
     DIR="$( cd -P "$( dirname "$SOURCE"  )" && pwd  )"
     SOURCE="$(readlink "$SOURCE")"
     [[ $SOURCE != /*  ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
 done
 DIR="$( cd -P "$( dirname "$SOURCE"  )" && pwd  )"
 shells=${DIR}
trueCmd=`which true`
sleepCmd=`which sleep`
#continuously call the realtime shell script
while [ $trueCmd ]; do
$sleepCmd 1s
$shells/realtime&
done

