#! /bin/bash

# source cfg file
. /usr/local/IPTVAgent/cfg/iptvagent.cfg

# source streamInfo
. $modulePath/streamInfo

if [ -d $streamingRunPath ]; then
    for pidFile in `ls $streamingRunPath`
        do
            name=${pidFile%.*}
            pid=`head -1 $streamRunPath/$pidFile`
            getStreamInfo $name $pid
        done
fi
