#!/bin/bash
shells=/home/suguannan/MyShells
PATH=$PATH:$shells
. $shells/insert
recordTime=`date -d today +"%Y-%m-%d %H:%M:%S"`
rst=$(/bin/cat /proc/net/dev \
        |sed 's/':'/''/' \
	| /usr/bin/awk  -F' '  ' NR>2 {   
        port="\""$1"\""" "port;  
        byteIn=$2" "byteIn;
        byteOut=$10" "byteOut;
        packetIn=$3" "packetIn;
        packetOut=$11" "packetOut
         }END{print port",";print byteIn",";print byteOut",";print packetIn",";print packetOut}' \
	)
port=$(echo $rst | awk -F ',' '{print $1}')
byteIn=$(echo $rst | awk -F ',' '{print $2}')
byteOut=$(echo $rst | awk -F ',' '{print $3}')
packetIn=$(echo $rst | awk -F ',' '{print $4}')
packetOut=$(echo $rst | awk -F ',' '{print $5}')
#define parameter arrays
portArray=(`echo ${port%?}`)
byteInArray=(`echo ${byteIn%?}`)
byteOutArray=(`echo ${byteOut%?}`)
packetInArray=(`echo ${packetIn%?}`)
packetOutArray=(`echo ${packetOut%?}`)
#iterate the arrays
len=${#portArray[@]}
for((i=0;i<$len;i++))
   do 
      SQLINSERT="insert into traffic(port,byteIn,byteOut,packetIn,packetOut,recordTime,server) values(${portArray[i]},${byteInArray[i]},${byteOutArray[i]},${packetInArray[i]},${packetOutArray[i]},\"$recordTime\",\"localcent\");"
      echo $SQLINSERT
      insert $SQLINSERT
   done
