#!/bin/bash
#get the real path of parent folder
SOURCE="$0"
while [ -h "$SOURCE"  ]; do # resolve $SOURCE until the file is no longer a symlink
    DIR="$( cd -P "$( dirname "$SOURCE"  )" && pwd  )"
    SOURCE="$(readlink "$SOURCE")"
    [[ $SOURCE != /*  ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE"  )" && pwd  )"
shells=${DIR}
. $shells/insert
hostnameCmd=`which hostname`
server=`$hostnameCmd`
dateCmd=`which date`
catCmd=`which cat`
sedCmd=`which sed`
awkCmd=`which awk`
echoCmd=`which echo`
recordTime=`$dateCmd -d today +"%Y-%m-%d %H:%M:%S"`
rst=$($catCmd /proc/net/dev \
        |$sedCmd 's/':'/''/' \
	|$awkCmd  -F' '  ' NR>2 {   
        port="\""$1"\""" "port;  
        byteIn=$2" "byteIn;
        byteOut=$10" "byteOut;
        packetIn=$3" "packetIn;
        packetOut=$11" "packetOut
         }END{print port",";print byteIn",";print byteOut",";print packetIn",";print packetOut}' \
	)
port=$($echoCmd $rst | $awkCmd -F ',' '{print $1}')
byteIn=$($echoCmd $rst | $awkCmd -F ',' '{print $2}')
byteOut=$($echoCmd $rst | $awkCmd -F ',' '{print $3}')
packetIn=$($echoCmd $rst | $awkCmd -F ',' '{print $4}')
packetOut=$($echoCmd $rst | $awkCmd -F ',' '{print $5}')
#define parameter arrays
portArray=(`$echoCmd ${port%?}`)
byteInArray=(`$echoCmd ${byteIn%?}`)
byteOutArray=(`$echoCmd ${byteOut%?}`)
packetInArray=(`$echoCmd ${packetIn%?}`)
packetOutArray=(`$echoCmd ${packetOut%?}`)
#iterate the arrays
len=${#portArray[@]}
for((i=0;i<$len;i++))
   do 
      SQLINSERT="insert into traffic(port,byteIn,byteOut,packetIn,packetOut,recordTime,server) values(${portArray[i]},${byteInArray[i]},${byteOutArray[i]},${packetInArray[i]},${packetOutArray[i]},\"$recordTime\",\"$server\");"
      $echoCmd $SQLINSERT
      insert $SQLINSERT
   done
