#! /bin/bash

#**********************************************************
#   Created on 2017-02-13 by liuxiaohu
#   
#   iptvagent       This shell scripts related to start
#                   and stop of the iptv agent process
#   
#   chkconfig: 2345 80 30
#   description: iptv agent service
#
#**********************************************************

# source iptv agent functions
. /usr/local/IPTVAgent/lib/functions

BASENAME=`basename $0`
RETVAL=0

# start iptvagent
start() {
    local count=`ps -ef|grep iptvagentd|grep -v grep|wc -l`
    if [ $count -eq 0 ]; then
        startAgent
        RETVAL=$?
    else
        echo -e "[\033[1;31mERROR:\033[0m] IPTVAgent has been started, please try restart instead"
        RETVAL=1
    fi
    echo -n "start iptvagent: "
    [ $RETVAL -eq 0 ] && echo_success
    [ $RETVAL -eq 1 ] && echo_failure
    echo
    return $RETVAL
}

# stop iptvagent
stop() {
    local count=`ps -ef|grep iptvagentd|grep -v grep|wc -l`
    if [ $count -eq 0 ]; then
        echo -e "[\033[1;31mERROR:\033[0m] IPTVAgent not running, please start first"
        RETVAL=1
    else
        stopAgent
        RETVAL=$?
    fi
    echo -n "stop iptvagent: "
    [ $RETVAL -eq 0 ] && echo_success
    [ $RETVAL -eq 1 ] && echo_failure
    echo
    return $RETVAL
}

# restart iptvagent
restart() {
    stop
    start
}

# status of iptvagent
iptvstatus() {
    local count=`ps -ef|grep iptvagentd|grep -v grep|wc -l`
    if [ $count -eq 0 ]; then
        echo -e "[\033[1;32mSTATUS:\033[0m]IPTVAgent not running."
    else
        echo -e "[\033[1;32mSTATUS:\033[0m] IPTVStreaming is running."
    fi
}

# service command
case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    status)
        iptvstatus
        ;;
    *)
        echo -e $"[\033[1;32mUsage:\033[0m] $BASENAME {start|stop|restart|status}"
        exit 1
esac

exit $?
