#! /bin/bash

# source cfg file
. /usr/local/IPTVAgent/cfg/iptvagent.cfg

#continuously call the realtime shell script
while true 
do
    sleep $realtimeInterval
    $modulePath/realtime > /dev/null 2>&1 &
done

